// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWN_7MToxrBObzq8OzLxESPFnNxO-2Ew',
    appId: '1:847247867591:web:0319619b4cd144f9e088e2',
    messagingSenderId: '847247867591',
    projectId: 'patrullapp-3292c',
    authDomain: 'patrullapp-3292c.firebaseapp.com',
    storageBucket: 'patrullapp-3292c.firebasestorage.app',
    measurementId: 'G-65SSPNLRF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmPxy9-9AAPJGL-yt8eedCHPKnvRSdFU',
    appId: '1:847247867591:android:0628a036d9ad5137e088e2',
    messagingSenderId: '847247867591',
    projectId: 'patrullapp-3292c',
    storageBucket: 'patrullapp-3292c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7DAn6TUyoIINYgmn0xVQQtgNypgItLc',
    appId: '1:847247867591:ios:35501792ecc21990e088e2',
    messagingSenderId: '847247867591',
    projectId: 'patrullapp-3292c',
    storageBucket: 'patrullapp-3292c.firebasestorage.app',
    iosBundleId: 'com.example.patrullapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr7DAn6TUyoIINYgmn0xVQQtgNypgItLc',
    appId: '1:847247867591:ios:35501792ecc21990e088e2',
    messagingSenderId: '847247867591',
    projectId: 'patrullapp-3292c',
    storageBucket: 'patrullapp-3292c.firebasestorage.app',
    iosBundleId: 'com.example.patrullapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcWN_7MToxrBObzq8OzLxESPFnNxO-2Ew',
    appId: '1:847247867591:web:e8a51dff95fee698e088e2',
    messagingSenderId: '847247867591',
    projectId: 'patrullapp-3292c',
    authDomain: 'patrullapp-3292c.firebaseapp.com',
    storageBucket: 'patrullapp-3292c.firebasestorage.app',
    measurementId: 'G-224B42LTF8',
  );
}
